[preview]
max_width = 1200
max_height = 1200

[tasks]
# No limits to image size to preview
image_bound = [0, 0]

[opener]
open = [
    { run = 'imv "$@"', desc = "See image", for = "linux" },
    { run = 'mpv "$@"', desc = "Play video", for = "linux" },
    { run = 'zathura "$@"', desc = "Read", for = "linux" },
    { run = 'zen-browser "$@"', desc = "Open in browser", for = "linux" },
]

[open]
prepend_rules = [
    { mime = "image/png", use = [ "see image" ] },
    { mime = "image/jpg", use = [ "see image" ] },
    { mime = "image/webp", use = [ "see image" ] },
    { mime = "image/gif", use = [ "open in browser" ] },
    { mime = "video/*", use = [ "play video" ] },
    { mime = "application/pdf", use = [ "read" ] },
]
